### ISSUE TITLE
Cannot scroll my listview anymore when if I use setRightSwipeEnabled or setLeftSwipeEnabled

### ISSUE THREAD

**Issue by luxsypher** [daimajia/AndroidSwipeLayout#105]
Hi, i am using a BaseSwipeAdapter. 
In my cells I want to enable or disable swipe (independently from one cell to another).

To do so I am using this :

    @Override
    public View generateView(int i, ViewGroup viewGroup)  {
        final ProductCellView cell = ProductCellView_.build(activity);
     ...
        // enable swipe left and right
        cell.swipeLayout.setDragEdges(SwipeLayout.DragEdge.Left, SwipeLayout.DragEdge.Right);
        // When using multiple drag edges it's a good idea to pass the ids of the views that you're using for the left, right, top bottom views (-1 if you're not using a particular view)
        cell.swipeLayout.setBottomViewIds(R.id.left_swipe_view, R.id.right_swipe_view, SwipeLayout.EMPTY_LAYOUT, SwipeLayout.EMPTY_LAYOUT);

        cell.swipeLayout.setRightSwipeEnabled(!disableRightSwipe);
        cell.swipeLayout.setLeftSwipeEnabled(!disableLeftSwipe);

the problem is by using setRightSwipeEnabled, or setLeftSwipeEnabled. 
It actually disable the scroll of my listview, defeating the purpose of a ListView.

**Comment by HarshEvilGeek** [comment]
This might take some time to fix. I'll try and get on it next weekend (21st)

**Comment by luxsypher** [comment]
Thanks you, I really need it :)

**Comment by luxsypher** [comment]
Any progress ?

**Comment by daimajia** [comment]
@luxsypher Try the latest version.

**Comment by daimajia** [comment]
@luxsypher Sorry fot the late reply on this issue, actually there was a big refracting of the code, which have solved a lot of bugs...

**Comment by luxsypher** [comment]
Solved with the new version.

**Comment by daimajia** [comment]
@luxsypher  Great!

**Comment by gurmeet-global** [comment]
`public class SwipeContactAdapter extends RecyclerSwipeAdapter<SwipeContactAdapter.ViewHolder> {

    private Context mContext;
    private ArrayList<DataObjectVO> mContactListData;

    public SwipeContactAdapter(Context context, ArrayList<DataObjectVO> contactListData) {
        this.mContext = context;
        this.mContactListData = contactListData;
    }


    @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View itemView = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.swipe_adapter_contact_item, parent, false);
        return new ViewHolder(itemView);
    }

    @Override
    public void onBindViewHolder(final ViewHolder holder, final int position) {

        holder.swipeLayout.setShowMode(SwipeLayout.ShowMode.LayDown);


        holder.llSwipeMultipal.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                UtilityMethods.showToast(mContext, "item click", Toast.LENGTH_SHORT);
            }
        });

       /* holder.swipeLayout.addSwipeListener(new SimpleSwipeListener() {
            @Override
            public void onOpen(SwipeLayout layout) {
                YoYo.with(Techniques.Tada).duration(500).delay(100).playOn(layout.findViewById(R.id.trash));
            }
        });*/
        holder.dotsImageView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                if (mItemManger.isOpen(position)) {
                    holder.swipeLayout.close();
                } else {
                    holder.swipeLayout.open();
                }

               /* mItemManger.removeShownLayouts(holder.swipeLayout);
                mItemManger.closeAllItems();*/
            }
        });

        holder.mClassifyTextView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                holder.swipeLayout.close();
            }
        });


        holder.nameTextView.setText(mContactListData.get(position).getName());
        holder.categoryTextView.setText(mContactListData.get(position).getFriendId());


        **for (int i = 0; i < mContactListData.size(); i++) {
            if (i % 2 == 0) {
                Logger.debug("swipe disable "+ i);
                holder.swipeLayout.setRightSwipeEnabled(false);
                holder.swipeLayout.setLeftSwipeEnabled(false);
                holder.swipeLayout.setSwipeEnabled(false);
            } else {
                Logger.debug("swipe enable "+ i);
                holder.swipeLayout.setRightSwipeEnabled(true);
                holder.swipeLayout.setLeftSwipeEnabled(true);
                holder.swipeLayout.setSwipeEnabled(true);
            }
        }**
    }

    @Override
    public int getItemCount() {
        return mContactListData.size() > 0 ? mContactListData.size() : 0;
    }

    @Override
    public int getSwipeLayoutResourceId(int position) {
        return R.id.swipe;
    }

    public class ViewHolder extends RecyclerView.ViewHolder {

        private TextView nameTextView, categoryTextView, mClassifyTextView, mShareSecrateTextView, mMoodtalkTextView, mDotsOptionTextView;
        private CircleImageView circleImageView;
        private SwipeLayout swipeLayout;
        private LinearLayout llSwipeMultipal, llSwipeRemove;
        private ImageView dotsImageView;


        public ViewHolder(View view) {
            super(view);

            swipeLayout = (SwipeLayout) view.findViewById(R.id.swipe);
            llSwipeMultipal = (LinearLayout) view.findViewById(R.id.ll_swipeChat);
            llSwipeRemove = (LinearLayout) view.findViewById(R.id.ll_swipeRemove);

            swipeLayout.addDrag(SwipeLayout.DragEdge.Left, llSwipeRemove);
            swipeLayout.addDrag(SwipeLayout.DragEdge.Right, llSwipeMultipal);

            mClassifyTextView = (TextView) view.findViewById(R.id.txt1);
            mShareSecrateTextView = (TextView) view.findViewById(R.id.txt2);
            mMoodtalkTextView = (TextView) view.findViewById(R.id.txt3);
            mDotsOptionTextView = (TextView) view.findViewById(R.id.txt4);

            nameTextView = (TextView) view.findViewById(R.id.name_tv);
            categoryTextView = (TextView) view.findViewById(R.id.category_tv);
            circleImageView = (CircleImageView) view.findViewById(R.id.image_view);

            dotsImageView = (ImageView) view.findViewById(R.id.overflow_imageview);

        }
    }
}
`
I would like to disable some items not swipable but in SwipeLayout class  methods setRightSwipeEnabled(false) , setLeftSwipeEnabled(false), setSwipeEnabled(false) are not disable swipe in recycle view items. How i can solved this issue?
