### ISSUE TITLE
  setMode(Attributes.Mode.Single) on RecyclerSwipeAdapter dont works

### ISSUE THREAD

**Issue by TheLester** [daimajia/AndroidSwipeLayout#107]
setMode(Attributes.Mode.Single) on RecyclerSwipeAdapter do not works. Wokred on BaseSwipeAdapter

**Comment by TheLester** [comment]
forgot to call mItemManger.bindView(swipeViewHolder.itemView, position); Its not clear for the first time

**Comment by smileman** [comment]
Thanks, man! You answer helped me.
