### ISSUE TITLE
is it possible to configure the offset to automatic swipe?

### ISSUE THREAD

**Issue by JMPergar** [daimajia/AndroidSwipeLayout#114]
I mean for example, when I drag de row a 20% I wish to complete de swipe (open item) if I finish touch event. Actually onHandRelease always cancel (close item), only open if gesture velocity is bigger than 0. I want open items by position of swipe too.

If actually this function isn't supported, do you think is difficult to implement? I could to develop a PR...

**Comment by JMPergar** [comment]
I think that it's possible modifying onViewReleased, processSurfaceRelease, processBottomPullOutRelease and processBottomLayDownMode if is possible to get LeftOffeset in this point.

**Comment by JMPergar** [comment]
Maybe it's possible to obtain Offset in this point with computeSurfaceLayoutArea...

**Comment by linfaxin** [comment]
this PR done it :) https://github.com/daimajia/AndroidSwipeLayout/pull/106

**Comment by JMPergar** [comment]
Are you going to merge?

**Comment by linfaxin** [comment]
I pulled the request, wait @daimajia check.

**Comment by daimajia** [comment]
Merged
