### ISSUE TITLE
Swipe from both edges?

### ISSUE THREAD

**Issue by youssefhg** [daimajia/AndroidSwipeLayout#115]
Hi, is there a reason why we cannot enable swiping from Left and Right at the same time?

**Comment by Rainer-Lang** [comment]
Oh that would be really great!
+1

**Comment by intrications** [comment]
@youssefhg You can do this. Are you using version 1.1.9?

**Comment by youssefhg** [comment]
Thanks @intrications. I did not know that there is a newer version.
