### ISSUE TITLE
Not able to close after deleting an item

### ISSUE THREAD

**Issue by SilleBille** [daimajia/AndroidSwipeLayout#117]
Hi,
I have successfully implemented SwipeLayout in my ListView based on your wiki. The only problem that I am facing is that, after deleting an item from List, the bottomview for the next item stays open. I tried calling close(true) after clicking the delete button. But, it's of no use.

Can you please check into this problem?

Thanks,
Dinesh

**Comment by youssefhg** [comment]
Try calling  swipeLayout.close() in fillValues() method of the adapter. This way every time the views are inflated it is closed by default.

**Comment by SilleBille** [comment]
@youssefhg  Thank you. That's a good way! Also, why not call closeAllItems() in onClick? (Just now found this way)

**Comment by mariem16** [comment]
swipeLayout.close() not working
