### ISSUE TITLE
Swipe deny does not work

### ISSUE THREAD

**Issue by andre1628** [daimajia/AndroidSwipeLayout#120]
Good day
We use AndroidSwipeLayout in our project and have a need to disable swipe of listview items in some cases. Tryed to do that with 2 ways:
1. SwipeLayout.setRightSwipeEnabled(false); This turns off swipe of listView items but it also disabled listView scroll (we need him to work), which we could not fix.
2. SwipeLayout.addSwipeDenier(new SwipeDenier()) where we were returnig true in case we need. But that has no effect. 
Tell pelase is this an issue or we do something wrong. Or tell please right way to deny swipe of listView items. 
thanks.

**Comment by daimajia** [comment]
How you ever tried  [`setSwipeEnabled`](https://github.com/daimajia/AndroidSwipeLayout/blob/master/library/src/main/java/com/daimajia/swipe/SwipeLayout.java#L959) ?

**Comment by andre1628** [comment]
No. Have tryed right now. Swipe is disabled. And listView is scrolling. My problem is solved.

**Comment by andre1628** [comment]
Goog day. Have one problem with method SwipeLayout.setSwipeEnabled(). As i said for listView swipe was disabled and listView was scrolling but items became unclickable(and we need to click them). Tell please how this could be fixed. Thanks

**Comment by luxsypher** [comment]
Sounds like this issue [105](https://github.com/daimajia/AndroidSwipeLayout/issues/105) ?

**Comment by andre1628** [comment]
Yes. Partially it is like 105, but as we use only right swipe it is enought for us to disable swipe at all, command setSwipeEnable(false) does this, and list view continue scrolling. But as I wrote earlier the items became unclickable. That is our problem.

Daimajia, can you tell should we expect solution of this isue in near days or it is unknown now wnen it will be solved? Thank you.

**Comment by daimajia** [comment]
@andre1628 @luxsypher  Hey guy, sorry for my late,  have you ever tried the latest version? I think we have fixed this issue.

**Comment by luxsypher** [comment]
@daimajia 
I am using this version :

      compile "com.daimajia.swipelayout:library:1.2.0@aar"
Currently, the sample is not working, more than that, the view is always dragable on the right, never on the left, and If I add another bottom view, only one is displayable: always the right one


Here is my code :

XML 

    <com.daimajia.swipe.SwipeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/swipe_layout"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    
    <LinearLayout
        android:id="@+id/right_swipe_view"
        android:layout_width="110dp"
        android:layout_height="match_parent"
        android:background="#F0F0F0"
        android:clickable="false"
        android:orientation="horizontal">


    </LinearLayout>
    


    
      <LinearLayout
         android:id="@+id/left_swipe_view"
         android:layout_width="110dp"
         android:layout_height="match_parent"
         android:background="#F0F0F0"
         android:clickable="false"
         android:gravity="center"
         android:orientation="horizontal">


     </LinearLayout>
     

    
    <LinearLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        android:padding="4dp">
    </LinearLayout>
    

    </com.daimajia.swipe.SwipeLayout>


View holder

    public class ProductViewHolder {

       @InjectView(R.id.swipe_layout)
        public SwipeLayout swipeLayout;

        public ProductViewHolder(View view) {
            ButterKnife.inject(this, view);
            swipeLayout.addDrag(SwipeLayout.DragEdge.Left, view.findViewById(R.id.right_swipe_view));
        }

    }

Adapter: 

    public class ProductAdapter extends BaseSwipeAdapter {
    [...]
    @Override
    public View generateView(int i, ViewGroup viewGroup) {
        return inflater.inflate(R.layout.cell_product, viewGroup, false);
    }

    @Override
    public void fillValues(int i, View view) {
        final ProductViewHolder holder = new ProductViewHolder(view);
        [...]
    }

    [...]
    }

**Comment by luxsypher** [comment]
Everything is working. 
Nice job.

**Comment by daimajia** [comment]
@105 Solved,  close now.
