### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: com.daimajia.swipe.SwipeLayout

### ISSUE THREAD

**Issue by RedRiven** [daimajia/AndroidSwipeLayout#121]
Caused by: java.lang.NoClassDefFoundError: com.daimajia.swipe.SwipeLayout

**Comment by daimajia** [comment]
Pretty sure that you must import this project in wrong way.

Can you describe how you imported ?

**Comment by daimajia** [comment]
No response.

**Comment by RedRiven** [comment]
sorry,I haven't used it for a long time.
