### ISSUE TITLE
Showning unknown behaviour in Samsung S3 and few other devices while working well in other devices

### ISSUE THREAD

**Issue by myandroidprojectid** [daimajia/AndroidSwipeLayout#122]
I've added three textviews on the right hand side and one textview on left hand side to show when the user swipes. But on S3  sometimes only one textview is visible on right hand side as shown in the images below.

![screenshot_2015-04-01-18-07-01](https://cloud.githubusercontent.com/assets/6511730/6941320/7e0bca82-d89c-11e4-8543-699470dd87fd.png)

![screenshot_2015-04-01-18-06-52](https://cloud.githubusercontent.com/assets/6511730/6941324/839a5428-d89c-11e4-8903-a200642ce0e4.png)

While sometimes all the three textviews on the right hand side are visible but in this case the left hand side textview takes extra space as shown in images below.

![screenshot_2015-04-01-18-07-22](https://cloud.githubusercontent.com/assets/6511730/6941330/8e93bfcc-d89c-11e4-812c-dc3bcbf303fe.png)

![screenshot_2015-04-01-18-07-35](https://cloud.githubusercontent.com/assets/6511730/6941334/93978b84-d89c-11e4-9ed9-05198d6cdf02.png)

The same code is working well in Samsung S4, Note 2, Tab 3, Moto G.

**Comment by linfaxin** [comment]
try this PR https://github.com/daimajia/AndroidSwipeLayout/pull/106

**Comment by uidq1290** [comment]
已收到

**Comment by HeroGentry** [comment]
想创业，开网店，低投资，高收入，叫你月月赚翻，美滋滋。本店诚招代理商，包教包会。QQ:2020633271旺旺:梦凌love13

**Comment by Dieselkaka** [comment]
谢谢，已收到
