### ISSUE TITLE
Displaying problem when playing with the visibility of elements in certains rows

### ISSUE THREAD

**Issue by Name-less** [daimajia/AndroidSwipeLayout#129]
Hello,

As you can see on this images, there is a displaying problem when i modify the visibility of some elements.

If there is an element of a row with a GONE visibility, it seems the the same element in other row became INVISIBLE and the displaying is weird.

Also, when I have more than 4 rows on my listView, some elements in different rows are hiden by nothing and just half displaying ... (first image, row 2, after Match there is a 6 half displayed ...)

This change randomly (it seems) when going in landscape and going back on portrait. Sometimes it is good, some times not ...

This is really disapointing because the library is awesome !!! Good job !

Thanks

Weird Displaying : 

![screenshot_2015-04-14-21-55-13](https://cloud.githubusercontent.com/assets/10023703/7146339/26de4e90-e2f3-11e4-844a-c8c41be79fac.png)

![capture d ecran 2015-04-14 a 21 59 48](https://cloud.githubusercontent.com/assets/10023703/7146343/35c31b20-e2f3-11e4-8d84-52013615c71d.png)

Normal displaying : 

![screenshot_2015-04-14-22-12-08](https://cloud.githubusercontent.com/assets/10023703/7146372/5e714010-e2f3-11e4-9f60-b39b6cbc9ee2.png)

NL

**Comment by daimajia** [comment]
I relesed a v1.2.0, please have a try.

**Comment by Name-less** [comment]
Thanks for the release, but I am having the displaying problem
With the new release i got :

Normal displaying when I just start the app

![screenshot_2015-04-21-11-26-05](https://cloud.githubusercontent.com/assets/10023703/7249250/5cf563a8-e819-11e4-911f-23d631c3d77d.png)

Weird displaying when I scroll down until the last element and come back to the first one : 

![screenshot_2015-04-21-11-25-10](https://cloud.githubusercontent.com/assets/10023703/7249286/a26f3fc6-e819-11e4-9d2b-5289b0d97788.png)

**Comment by linfaxin** [comment]
Is your listview's adapter is subclass of BaseSwipeAdapter?

**Comment by Name-less** [comment]
yep !

**Comment by linfaxin** [comment]
Try use FrameLayout instead of SwipeLayout, to look is it displaying weird.

**Comment by Name-less** [comment]
hum weird, I try with frameLayout, everything was good, I came back to swipe layout, It was good to. I tried to add/delete element and everything stay well displayed ... I tell you if a found a configuration where the displaying is not good after scrolling and good with the frameLayout
