### ISSUE TITLE
SurfaceView click listener breaks swipe in library:1.1.9@aar (working on master branch from GitHub)

### ISSUE THREAD

**Issue by leinardi** [daimajia/AndroidSwipeLayout#131]
It seems that the version 1.1.9 available on maven breaks the handling of the swipe when the click listener is attached to the SurfaceView. It works properly using the latest code from github (library project).

I tested only the RecyclerView example.

To test the swipe/click on one item of the list I just added this code taken from MyActivity.java to the method onBindViewHolder() inside the RecyclerViewAdapter.java:

```
        viewHolder.swipeLayout.getSurfaceView().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(mContext, "Click on surface", Toast.LENGTH_SHORT).show();
                Log.d(RecyclerViewAdapter.class.getName(), "click on surface");
            }
        });
```

Using the code on GitHub both the click and swipe work properly. With 1.1.9@aar the swipe gesture is ignored end only the click is handled.

I created a simple project where you can reproduce the problem: https://dl.dropboxusercontent.com/u/202594/BrokenClick.zip

To do this simply enable either the project library (working click/swipe) or the 1.1.9@aar (broken swipe) from the build.gradle.

**Comment by daimajia** [comment]
@leinardi Hey, thanks for your feedback, can you test the latest master branch, to check if the latest code solved this problem.

**Comment by amswf** [comment]
Nice function。

**Comment by leinardi** [comment]
Hi @daimajia, thanks for the reply. As is said in the title the latest master bransh works properly.
Have you already scheduled a date for the next release on maven?

Roberto

**Comment by leinardi** [comment]
Hi @daimajia, release v1.2.0 seems to have solved the problem.

Thanks, Roberto

**Comment by daimajia** [comment]
@leinardi Awesome!

**Comment by daimajia** [comment]
Especially also need to thanks @linfaxin for his pull request.

**Comment by leinardi** [comment]
I also thank @linfaxin, but in this case the working code was already on master branch, even before his pull request. It was missing only the publication of Maven :-)
