### ISSUE TITLE
Add Contributing Documentation

### ISSUE THREAD

**Issue by jpshelley** [daimajia/AndroidSwipeLayout#136]
@daimajia we should consider adding a doc called CONTRIBUTING.
As mentioned by github guidelines: https://guides.github.com/activities/contributing-to-open-source/
It can be rather simple but thought I'd keep an issue open until one is created.

**Comment by daimajia** [comment]
Great idea.  I'll do this tomorrow.

**Comment by daimajia** [comment]
BTW. If you have any idea on this files's content, please feel free to comment here. E.g on the communication rules, how to show the contributors ( need a photo or not... ), every kind of idea will be ok.

for example: I actually pretty want to have contributor's photo, it will be lovely when shown to all the developers. ^^

**Comment by jpshelley** [comment]
@daimajia Ha great idea. I'd just go with their github photos but thats just me. I would take a look at other popular libs to decide the content: for example all of square's libs have something like this: https://github.com/square/retrofit/blob/master/CONTRIBUTING.md

**Comment by jpshelley** [comment]
I don't think we need a CLA though.

**Comment by daimajia** [comment]
The meaning of CLA is ?

**Comment by daimajia** [comment]
My idea:
Two part of this file. 
- Show every contributors.
- Show new comers how to contribute.

**Comment by jpshelley** [comment]
@daimajia CLA is a  Individual Contributor License Agreement (CLA). Basically a way for them to sign an agreement with contribution. Square's libraries have them but since we aren't an organization it's not needed. Thats all I was trying to say.

And yes that would be a good idea I think. Maybe still look at other popular libraries and see what they put.

**Comment by daimajia** [comment]
@jpshelley Ok, I'll draft an early version tomorrow. Any idea, comment here.

**Comment by jpshelley** [comment]
@daimajia Sounds good. My only initial thoughts are regardless of contributor, fork+pull request would be best method. I think branch+pull request should be left up to huge feature or huge core differences that the owner (aka you) should be left to do. And no commits straight to master. That has to be on the maintainers.
On that note, listing the maintainers in the contrib with mention of being able to contact via gitter

**Comment by daimajia** [comment]
@jpshelley Good idea, I'm starting to obey this.
Check this.  
https://github.com/daimajia/AndroidSwipeLayout/blob/contributor/contributing.md

**Comment by jpshelley** [comment]
@daimajia Looks good! Minor thing I would capitalize the word so: CONTRIBUTING.md. Otherwise feel free to close this issue!
