### ISSUE TITLE
Remove all Swipe Listeners

### ISSUE THREAD

**Issue by voluntadpear** [daimajia/AndroidSwipeLayout#138]
It will be very useful for me to have a removeAllSwipeListeners() method like the removeAllSwipeDeniers() one.

**Comment by jpshelley** [comment]
@voluntadpear Feel free to create a pull request! I know some of the maintainers are busy with college finals these next 2 weeks.

**Comment by daimajia** [comment]
Fixed.

**Comment by amrfaisal** [comment]
When will be this fix released ?
