### ISSUE TITLE
generateView int position is always 0

### ISSUE THREAD

**Issue by vaggelis-net** [daimajia/AndroidSwipeLayout#14]
Why the position is always 0 when generateView is called?
I want to make a listview and i hold a reference to a list with all the objects in the swipeadapter.
I have a trash imageview in the bottom view (just like in the tutorial) which when clicked it deletes that item, but i can't notify the adapter with the position since it's always 0. So the wrong item gets deleted.

**Comment by ShreyashMahajan** [comment]
@de-Stan 
@angelen10 
I am not getting this method in listview or in swipeLayout. Please let me know from where i can have this method. Where to handled it. I want to implement the listview item click listener but it is always calling when i close the swipeLayout.

Please help me in this.

**Comment by de-Stan** [comment]
Sorry i can't understand what you asking. Some code could be helpful to see what you are up to.

**Comment by ShreyashMahajan** [comment]
@de-Stan 
The simple thing is, i want to implement the OnItemClick on listview with your example. but the problem is, whenever i do swipe close, it called the onItemClick for listview. That should not be happen.

That is the the issue. Even i am not getting any method as explained in above comment.

**Comment by de-Stan** [comment]
I haven't used the librady almost a year now, but i didn't have any problems as you describe. Maybe some things change or broke with an update? Or are you doing something wrong in your side?
Some code should give some more info, also @daimajia should notice this also.

**Comment by ShreyashMahajan** [comment]
I have just check your repo and it have same issue and also implement that in my project which also have same issue.

Please just get fresh copy of your repo and try it.
