### ISSUE TITLE
How to enable swipe gesture on clickable views

### ISSUE THREAD

**Issue by phanghos** [daimajia/AndroidSwipeLayout#140]
First of all, let me say that I love your library; it is very useful, and I have had no trouble with it so far. I've been working on a Reddit client app, and so I have an adapter of posts with each row being a CardView containing a post's info. The swipe gesture works fine, but the problem is that sometimes the title of a post is long and occupies most of the card's content; and since the TextView for the post's title is clickable (starting another activity), the swipe gesture doesn't work if the gesture starts on that View. So, with some TextView's occupying most of the card's content, there is little space for the swipe gesture to work. In short I want the swipe gesture to work on the whole card, even on clickable views.

Thanks!

**Comment by jpshelley** [comment]
@phanghos Where is your SwipeLayout located? Inside the card, outside the card? If you could leave a gist of your layout+code might help with the issue. One thing to note is the way Android dispatches touch events. Android starts high level and works its way down through child views, if at any time a view returns true for its 'onInterceptTouchEvent' then it starts consuming the view and any other touchEvents won't get called.

**Comment by phanghos** [comment]
Thank you for such a quick reply.

Here is the layout for each row in the adapter. I removed most of the views in the card and left only the TextView that is causing trouble. I also removed the bottom layout, which includes basically buttons for sharing and saving a post.

    <?xml version="1.0" encoding="utf-8"?>
    <com.daimajia.swipe.SwipeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/swipe_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="wrap_content"
        android:layout_height="match_parent">

        

    </RelativeLayout>

    
    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.v7.widget.CardView
            xmlns:card_view="http://schemas.android.com/apk/res-auto"
            android:id="@+id/card_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginTop="5dp"
            android:layout_marginBottom="5dp"
            card_view:cardCornerRadius="3dp"
            card_view:cardElevation="1dp">

            <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                android:id="@+id/top_layout"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:paddingLeft="5dp"
                android:paddingTop="10dp"
                android:paddingRight="5dp"
                android:paddingBottom="10dp">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_marginLeft="15dp"
                    android:orientation="vertical">

                    <TextView
                        android:id="@+id/text_title"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_marginBottom="@dimen/activity_horizontal_margin"
                        android:textSize="15sp"
                        android:textColor="@color/primary_text" />


                </LinearLayout>

                

            </RelativeLayout>

        </android.support.v7.widget.CardView>

    </RelativeLayout>

    </com.daimajia.swipe.SwipeLayout>

In the activity that hosts the ListView I have this:

    @Override
    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
        Link link = (Link) adapter.getItem(position);
        String permalink = link.getPermalink();
        Intent i = new Intent(this, CommentsActivity.class);
        i.putExtra("permalink", permalink);
        startActivity(i);
    }

The above code works as expected. I want to start another activity showing the post's comments whenever clicking on any area of the card other than the title TextView (which would start a different activity).

Here is part of the code that is inside the adapter:

    @Override
    public View generateView(final int position, ViewGroup viewGroup) {
        View v = context.getLayoutInflater().inflate(R.layout.row_layout_temp, null);
        SwipeLayout layout = (SwipeLayout) v.findViewById(getSwipeLayoutResourceId(position));
        layout.setShowMode(SwipeLayout.ShowMode.LayDown);
        layout.setDragEdge(SwipeLayout.DragEdge.Right);
        return v;
    }

    @Override
    public void fillValues(final int position, View v) {
        Link link = objects.get(position);
        TextView title = (TextView) v.findViewById(R.id.text_title);
        title.setText(link.getTitle());
    }

There is where the problem lies. If I set an OnClickListener for the TextView title, the swipe gesture ceases to work on that View.

**Comment by linfaxin** [comment]
Try update your library version to v1.2.0

**Comment by phanghos** [comment]
@linfaxin That did the job! Thank you very much!
