### ISSUE TITLE
AndroidSwipeLayout-v1.1.8.jar

### ISSUE THREAD

**Issue by ouacyou** [daimajia/AndroidSwipeLayout#143]
Eclipse下的AndroidSwipeLayout-v1.1.8.jar包好像不是最新的吧

**Comment by daimajia** [comment]
Actually, I'm planing to stop supporing jar artifacts, cause jar package can not support  attributes definiation, after v1.1.8, the attributes is more important than before, i can not just cut it off and compile it to jar like usual.  So, try to use gradle or maven to build your new project.

**Comment by ouacyou** [comment]
Thx~
