### ISSUE TITLE
apply ViewHolder Pattern for the ListView SwipeLayout

### ISSUE THREAD

**Issue by kprathap23** [daimajia/AndroidSwipeLayout#165]
I am using listview with swipelayout library, i want to implement viewholder patten for the listview adapter.
Any sample snippet code ?

**Comment by daimajia** [comment]
Hey guy, the `ListViewAdapter` is extended from `BaseSwipeAdapter`, the `BaseSwipeAdapter` is using ViewHolder pattern currently. 
Check it https://github.com/daimajia/AndroidSwipeLayout/blob/master/library/src/main/java/com/daimajia/swipe/adapters/BaseSwipeAdapter.java#L51-L59

**Comment by kprathap23** [comment]
Thanks For the Great Library.
