### ISSUE TITLE
setOnItemClickListener not working

### ISSUE THREAD

**Issue by GuilhE** [daimajia/AndroidSwipeLayout#176]
In the latest version of this lib (1.2.0@aar) setOnItemClickListener it's never called don't know why. Reverted to 1.1.7 and it's working.

**Comment by skyfe79** [comment]
I have same problem on 1.2.0@aar library. Please fix it for us :)

**Comment by popescugeorgeviorel** [comment]
I think it's because the SwipeLayout's parent is not an AdapterView. The code in SwipeLayout only checks first child :

private boolean insideAdapterView() {
        return getAdapterView() != null;
    }

    private AdapterView getAdapterView() {
        ViewParent t = getParent();
        if (t instanceof AdapterView) {
            return (AdapterView) t;
        }
        return null;
    }

You can make you SwipeLayout be the root of the list item layout or you can modify the code to search recursive for all parents.
