### ISSUE TITLE
NPE in v1.2.0 - SwipeLayout.java line 901

### ISSUE THREAD

**Issue by tuckercr** [daimajia/AndroidSwipeLayout#180]
Hi,

I have had a crash report, although I'm unable to recreate myself:

0	java.lang.NullPointerException
1	at com.daimajia.swipe.SwipeLayout.onTouchEvent(SourceFile:901)
2	at android.view.View.dispatchTouchEvent(View.java:5568)
<snip>

I looked at the code and it occurs here:

![image](https://cloud.githubusercontent.com/assets/6718800/8431578/7751dd5a-1f08-11e5-8733-f9532941d3f8.png)

Any idea why getParent() would be null?  Could we add a null check here?

Regards,
Colin

**Comment by phileo** [comment]
same issue as #146
