### ISSUE TITLE
How to differentiate left swipe and right swipe

### ISSUE THREAD

**Issue by rex3du** [daimajia/AndroidSwipeLayout#186]
How to differentiate left swipe and right swipe? Currently, I need to trigger different functions when user swipe left and swipe right? Any Suggestions?? 

Thank you in advance

**Comment by fritzsche91** [comment]
I handled it by adding the following code to the **onStartOpen**(SwipeLayout swipeLayout) method from the added SwipeListener:
```java
                SwipeLayout.DragEdge dragEdge = swipeLayout.getDragEdge();

                this.isLeftToRightSwipe = SwipeLayout.DragEdge.Left.equals(dragEdge);
                if(this.isLeftToRightSwipe) {
                    // handle left to right swipe
                } else {
                    // handle right to left swipe
                }
```

**Comment by rex3du** [comment]
@fritzsche91 Thank you for solution. It works.
