### ISSUE TITLE
can't disable item in list view

### ISSUE THREAD

**Issue by lazypixelIn** [daimajia/AndroidSwipeLayout#19]
First of all awesome library man..
But there is only one problem i am facing i cant disable any listview item..
i try using is enable override mathod of adpter but still item is enabled..
please answer asap....

**Comment by gurmeet-global** [comment]
public class SwipeContactAdapter extends RecyclerSwipeAdapter<SwipeContactAdapter.ViewHolder> {

    private Context mContext;
    private ArrayList<DataObjectVO> mContactListData;

    public SwipeContactAdapter(Context context, ArrayList<DataObjectVO> contactListData) {
        this.mContext = context;
        this.mContactListData = contactListData;
    }


    @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View itemView = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.swipe_adapter_contact_item, parent, false);
        return new ViewHolder(itemView);
    }

    @Override
    public void onBindViewHolder(final ViewHolder holder, final int position) {

        holder.swipeLayout.setShowMode(SwipeLayout.ShowMode.LayDown);


        holder.llSwipeMultipal.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                UtilityMethods.showToast(mContext, "item click", Toast.LENGTH_SHORT);
            }
        });
        holder.dotsImageView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                if (mItemManger.isOpen(position)) {
                    holder.swipeLayout.close();
                } else {
                    holder.swipeLayout.open();
                }
            }
        });

        holder.mClassifyTextView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                holder.swipeLayout.close();
            }
        });


        holder.nameTextView.setText(mContactListData.get(position).getName());
        holder.categoryTextView.setText(mContactListData.get(position).getFriendId());


        **for (int i = 0; i < mContactListData.size(); i++) {
            if (i % 2 == 0) {
                Logger.debug("swipe disable "+ i);
                holder.swipeLayout.setSwipeEnabled(false);
            } else {
                Logger.debug("swipe enable "+ i);
                holder.swipeLayout.setSwipeEnabled(true);
            }
        }**


        // UtilityMethods.loadimage(mContactListData.get(position).getProfileImage(), holder.circleImageView);

        //   setAnimation(holder.itemView, position);
    }

    @Override
    public int getItemCount() {
        return mContactListData.size() > 0 ? mContactListData.size() : 0;
    }

    @Override
    public int getSwipeLayoutResourceId(int position) {
        return R.id.swipe;
    }

    public class ViewHolder extends RecyclerView.ViewHolder {

        private TextView nameTextView, categoryTextView, mClassifyTextView, mShareSecrateTextView, mMoodtalkTextView, mDotsOptionTextView;
        private CircleImageView circleImageView;
        private SwipeLayout swipeLayout;
        private LinearLayout llSwipeMultipal, llSwipeRemove;
        private ImageView dotsImageView;


        public ViewHolder(View view) {
            super(view);

            swipeLayout = (SwipeLayout) view.findViewById(R.id.swipe);
            llSwipeMultipal = (LinearLayout) view.findViewById(R.id.ll_swipeChat);
            llSwipeRemove = (LinearLayout) view.findViewById(R.id.ll_swipeRemove);

            swipeLayout.addDrag(SwipeLayout.DragEdge.Left, llSwipeRemove);
            swipeLayout.addDrag(SwipeLayout.DragEdge.Right, llSwipeMultipal);

            mClassifyTextView = (TextView) view.findViewById(R.id.txt1);
            mShareSecrateTextView = (TextView) view.findViewById(R.id.txt2);
            mMoodtalkTextView = (TextView) view.findViewById(R.id.txt3);
            mDotsOptionTextView = (TextView) view.findViewById(R.id.txt4);

            nameTextView = (TextView) view.findViewById(R.id.name_tv);
            categoryTextView = (TextView) view.findViewById(R.id.category_tv);
            circleImageView = (CircleImageView) view.findViewById(R.id.image_view);

            dotsImageView = (ImageView) view.findViewById(R.id.overflow_imageview);

        }
    }
}
 setSwipeEnabled(false) is not working to disable swipe. Is there anything that i have missed to disable swipe of an item.
