### ISSUE TITLE
When I swipe surface view, Listview intercepts the swipe gesture

### ISSUE THREAD

**Issue by bhaumiknsoni** [daimajia/AndroidSwipeLayout#21]
I have a bottom view with single button. When I swipe surface view more than bottom view width, Listview intercepts the swipe gesture.

**Comment by ansh7** [comment]
Any update on this?

**Comment by daimajia** [comment]
@ansh7  Sorry, still not solved, cause too busy recently...

**Comment by ansh7** [comment]
Any idea what's causing the problem. I can look at solving it myself and contributing the solution

**Comment by daimajia** [comment]
@ansh7 when swiping to open the SwipeLayout, we should disable the ListView's scroll, but i forgot to set it...

**Comment by daimajia** [comment]
Has been fixed now,  close this issue. Any problem, feel free to comment here.
