### ISSUE TITLE
java.util.zip.ZipException:Duplicate entry error with minSdkVersion 19 but not with 21/22

### ISSUE THREAD

**Issue by monkeyfdude** [daimajia/AndroidSwipeLayout#229]
I have limited experience with Android/Gradle. I get error below if I use `minSdkVersion 19` in gradle configuration below.

If I change it to `minSdkVersion 21` or `minSdkVersion 22`, then I do not get the error.

**Would you know the issue?**

----------------------------------------------------------------

> Error:Execution failed for task
> ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/daimajia/swipe/BuildConfig.class

    apply plugin: 'com.android.application'
    apply plugin: 'com.google.gms.google-services'
    
    android {
        compileSdkVersion 22
        buildToolsVersion "22.0.1"
        defaultConfig {
            minSdkVersion 19
            targetSdkVersion 22
            versionCode 1
            versionName "1.0"
            multiDexEnabled true
        }
    }
    
    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        compile "com.android.support:appcompat-v7:22.1.0"
        compile 'com.android.support:multidex:1.0.0'
        compile 'com.android.support:recyclerview-v7:22.0.0'
        compile 'com.google.android.gms:play-services-gcm:7.8.0'
        compile 'com.google.android.gms:play-services:7.8.0' 
        compile "com.daimajia.swipelayout:library:1.2.0@aar"
   
    }

**Comment by woolworthpaul** [comment]
i am facing a similar issue like yours. I tried changing the minSDKVersion to 21 everything working fine.But when i switch to 19 or less i get this very same error. 
Could you post the solution if you did get any? Thank you.

**Comment by flyliufu** [comment]
i also have this question, my util project  the same as my APP project  gradle compile wrong

**Comment by flyliufu** [comment]
java.util.zip.ZipException: duplicate entry

**Comment by flyliufu** [comment]
i also have this question, my util project the same as my APP project gradle compile wrong
java.util.zip.ZipException: duplicate entry  have any solution? thanks!

**Comment by flyliufu** [comment]
i also have this question, my util project packages name  the same as my APP project gradle compile wrong java.util.zip.ZipException: duplicate entry have any solution? thanks!

**Comment by arpitjindal97** [comment]
I am also getting same issue on API 19. Selecting 21 works fine.

**Comment by Hong-Ci-Yuan** [comment]
I have the same issue but i need to setting API in the 16

**Comment by Wissperwind** [comment]
I have the same issue. But I need to develop for API 19. I can't set the level to 21. What can I do?

**Comment by Igorshp** [comment]
Ran into similar issue upgrading from 16 to 19. Unfortunately moving past 19 is not an option at the moment.

Any advice would be much appreciated.

@Wissperwind have you found any solution to this?

**Comment by AzureIP** [comment]
In my case it was my fault. I developed a library, which included a jar. I thought that if I use this library, I had to include that jar again. That was wrong. The errors that lead me to the second jar include appeared because in the library I used additionally an aar, and I had to iclude that again.
