### ISSUE TITLE
No way to disable swipe gesture

### ISSUE THREAD

**Issue by IliaEremin** [daimajia/AndroidSwipeLayout#24]
I want to disable swipe gesture in certain case.
I try to set setDragEdge(null) but got NPE, try to swipeLayout.setEnabled(false) and it is not work.
Please add this feature or tell me how do it.

**Comment by silviahisham** [comment]
```setEnabled(false)``` does not disable the swipe gesture in 1.2.0

**Comment by EdbertChan** [comment]
@silviahisham : This is correct. You should just use setSwipeEnabled. setEnabled seems to do nothing. It should be marked as depreciated if it is not being used.

**Comment by AppDev666** [comment]
@daimajia thanks for the update.

**Comment by snehazanzane** [comment]
Hi,
setEnabled(false) is not working. Please suggest me how to do it.

**Comment by gurmeet-global** [comment]
Hi,
setSwipeEnabled(false)  is not working to disable swipe. How i can achieve functionality of enable and disable swipe on certain recycle view items. Please suggest .....

**Comment by gurmeet-global** [comment]
Hi , 
` holder.swipeLayout.setRightSwipeEnabled(false);
            holder.swipeLayout.setLeftSwipeEnabled(false);
            holder.swipeLayout.setSwipeEnabled(false);
            holder.swipeLayout.setEnabled(false);`

No one method is work to disable swipe. How i can do this task?

**Comment by gurmeet-global** [comment]
for (int i = 0; i < mContactListData.size(); i++) {
            if (i % 2 ==  0) {
                Logger.debug("Swipe " + false + " " + i);
               holder.swipeLayout.setLeftSwipeEnabled(false);
                holder.swipeLayout.setRightSwipeEnabled(false);
                holder.swipeLayout.setSwipeEnabled(true);
            } else {
                Logger.debug("Swipe " + true + " " + i);    
               holder.swipeLayout.setLeftSwipeEnabled(true);
                holder.swipeLayout.setRightSwipeEnabled(true);
                holder.swipeLayout.setSwipeEnabled(false);
            }
        }
I'm trying to disable some items in recycle view some should be enable but it's  disable/enable complete recycle view.

**Comment by wa1demar** [comment]
setSwipeEnabled(false) - works for me

**Comment by gobis** [comment]
Yes, setSwipeEnabled(false) - It works
