### ISSUE TITLE
ListView Item position issue

### ISSUE THREAD

**Issue by mohamedtawfik** [daimajia/AndroidSwipeLayout#307]
I implemented BaseSwipeAdapter on ListView. When I scroll down and up the returned index of item not correct. There is issue with recycling views. I also checked the library demo and it shows the same problem

**Comment by mohamedtawfik** [comment]
Any solution @daimajia  ?

**Comment by degina** [comment]
Same here. I don't know why this happening

**Comment by degina** [comment]
You should try issue #14.

**Comment by mohamedtawfik** [comment]
@daimajia :So, you should update the sample and not to implement listener at "generateView"

**Comment by mohamedtawfik** [comment]
@daimajia :So, you should update the sample and not to implement listener at "generateView"

**Comment by Kintanpatel4393** [comment]
I implemented BaseSwipeAdapter on ListView but not getting correct position,any one has solucation ?????
