### ISSUE TITLE
When ListView scrolling ,how can I close all the open(swiped) Items?

### ISSUE THREAD

**Issue by sleepingAnt** [daimajia/AndroidSwipeLayout#33]
Is there a feature , make it click an swiped(open) list item to close it? Or when ListView scrolling ,how can I close all the open(swiped) Items?
It just like this:
![222](https://cloud.githubusercontent.com/assets/1930918/4354969/338a5002-4245-11e4-9bb1-1f073783065b.gif)

**Comment by sudhiryadav** [comment]
Hi,

Is this feature included in the latest release.
