### ISSUE TITLE
swipe layout programmatically

### ISSUE THREAD

**Issue by aitbaali** [daimajia/AndroidSwipeLayout#359]
How can I swipe layout programmatically?

**Comment by afiqiqmal** [comment]
Open
`swipeLayout.open(true);`

Close
`swipeLayout.close(true);`

true to swipe animation
false to disabled animation

**Comment by aitbaali** [comment]
it works well, thanks.

**Comment by daimajia** [comment]
Thanks @afiqiqmal .

**Comment by harishvishwakarma** [comment]
@daimajia : How can we swipe programmatically with a specific leftOffset value?

**Comment by hsnmrd** [comment]
@harishvishwakarma did you find any solution for that?
