### ISSUE TITLE
Only activate the slide on certain conditions

### ISSUE THREAD

**Issue by BrandenSandahl** [daimajia/AndroidSwipeLayout#365]
Is there a way for me to do a check somewhere that only turns the slide functionality on if certain conditions are met? 

Basically, if a user does not have the proper authority, I would like for nothing to happen when they try to slide. 

Thanks!

**Comment by daimajia** [comment]
Check this method: [`setSwipeEnabled`](https://github.com/daimajia/AndroidSwipeLayout/blob/master/library/src/main/java/com/daimajia/swipe/SwipeLayout.java#L999-L1001)

**Comment by BrandenSandahl** [comment]
That's definitely what I am looking for. 

Where would you recommend I call it at? I tried calling it on onStartOpen and onUpdate but it still pulls the slider out a tiny bit before stopping it. 

Also, this is a fantastic library, thanks so much for taking your time on it.
