### ISSUE TITLE
BottomView items with drawable selector for pressed state

### ISSUE THREAD

**Issue by GuilhE** [daimajia/AndroidSwipeLayout#38]
My BottomVIew it's composed with two "buttons":

BottomView (LinearLayout):
*layout_width="200dp"
*android:layout_height="wrap_content"
*android:minHeight="90dp"
*android:orientation="horizontal"

Button1 (LinearLayout):
*android:layout_width="0dp"
*android:layout_height="match_parent"
*android:layout_weight="1"
...

--ImageView (with a selector for android:src)
--TextView

Button 2 (LinearLayout) equal to Button 1

My problem is with the selector state "pressed". Button 1 works fine but Button 2 or any other View I add as a button (3, 4,...) have his state "pressed" randomly changed when I click in other buttons or in the SurfaceView.

Can't figure out why. I was looking at your sample app but it doesn't include selectors for BottomView views.

Thanks for your time.

**Comment by daimajia** [comment]
No response.
