### ISSUE TITLE
部分手机 划开后自动关闭，好多人都这个问题，为啥作者不提一下呢

### ISSUE THREAD

**Issue by mingtang1079** [daimajia/AndroidSwipeLayout#380]
按照大家的解决方案，都没成功。。。

**Comment by beiliubei** [comment]
+1

**Comment by sumaniru** [comment]
试过他自带的adapter没  我发现魅族手机都会有这个问题  下了个demo发现 demo里的listview并不会这样，于是重新看了次wiki 发现他有个自带的adapter 用了 就好了。

**Comment by roshenLiang** [comment]
是啊 这控件有问题！！！

**Comment by daimajia** [comment]
duplicate with #413
