### ISSUE TITLE
onClick listener on surface view

### ISSUE THREAD

**Issue by scottagarman** [daimajia/AndroidSwipeLayout#39]
I'm trying to add an onClick listener to the surface view so that when bottom view is expanded and users click on the remaining visible surface view the swipe view toggle closed. When I add the click listener dragging breaks. Is this intended?

**Comment by daimajia** [comment]
https://github.com/daimajia/AndroidSwipeLayout/blob/master/demo/src/main/java/com/daimajia/swipedemo/MyActivity.java#L44 This feature has been added, close this issue right now. :-D
