### ISSUE TITLE
SwipeLayout 1327行语法错误？

### ISSUE THREAD

**Issue by huxiaotian123** [daimajia/AndroidSwipeLayout#397]
![image](https://cloud.githubusercontent.com/assets/14288168/20641870/754af648-b43c-11e6-97cd-61ccd5fdcd92.png)

**Comment by 838514984** [comment]
解决了吗？
我也遇到了

**Comment by MARGI3** [comment]
i got this too

**Comment by xesam** [comment]
作者估计已经放弃维护了，可以再来一波新的了。。哈哈哈
