### ISSUE TITLE
魅族手机侧滑自动关闭，求修复啊~~~~~！！！

### ISSUE THREAD

**Issue by MoonlightSW** [daimajia/AndroidSwipeLayout#399]
我用的是recyclerview，心痛~~~~~~~~~~~~~~~~~~

**Comment by zung** [comment]
我的也是，你解决了吗

**Comment by MoonlightSW** [comment]
@zung 解决了，换了一个框架！
_(:зゝ∠)_

**Comment by fuxianwen** [comment]
@MoonlightSW  求推荐 我也遇到了

**Comment by daimajia** [comment]
Duplicate with #317

**Comment by zung** [comment]
没有小米 魅族等手机，我们开发者是多么自在啊

**Comment by EricMikaelson** [comment]
可以参考demo中的 RecyclerViewExample 
1.继承 RecyclerSwipeAdapter 
2.imHolder.mSwipeLayout.setShowMode(SwipeLayout.ShowMode.LayDown);
3.mItemManger.bindView(imHolder.itemView, position);
4.mAdapter.setMode(Attributes.Mode.Single);
5.closeAllItems()
6.    @Override
    public int getSwipeLayoutResourceId(int position) {
        return R.id.recent_msg_item_swipeLayout;
    }

**Comment by daimajia** [comment]
没有会出问题的魅族手机，家里有一个魅族，也借了朋友的魅族，但是试了很多遍都没有什么异常....  要是有朋友寄一个，我可以花时间修复（修复后还回）。
