### ISSUE TITLE
Enabled Swiping with multiple DragEdges

### ISSUE THREAD

**Issue by ofermoshsaioff** [daimajia/AndroidSwipeLayout#40]
You should really consider adding the ability to swipe to multiple directions. I.E. - left and right, or left and top for example.

**Comment by iAviatorJose** [comment]
But is there any documentation related to this, on how to go with this.
A sample XML code will also suffice.

**Comment by daimajia** [comment]
@iAviatorJose It's not finished yet...

**Comment by HarshEvilGeek** [comment]
Yes, I'll try to add a little bit of documentation. Unfortunately, I've been shifted to something more urgent at my company, so I won't be able to finish this till the 20th (Jan). Once I get back to it, it shouldn't take more than a few days.

**Comment by iAviatorJose** [comment]
Great !!! I'll be waiting for the update @HarshEvilGeek  and @daimajia  :)

**Comment by intrications** [comment]
@HarshEvilGeek I've tried out your code and it works well for me.

What is the difference between ShowMode.LayDown and ShowMode.PullOut?

**Comment by HarshEvilGeek** [comment]
Great to hear.

I didn't add the modes. It's a simple styling difference though added by @daimajia. 

Laydown, makes it look like the background was there the whole time when you swipe (just lying below). Pullout makes it look like it's coming from the side of the screen. Switch them and play around with the app, and you'll see the difference.

**Comment by intrications** [comment]
@HarshEvilGeek Ah, I understand now.

I tried to work out who had added the modes through the git commits. Obviously didn't look well enough. Thanks anyway.

**Comment by intrications** [comment]
@HarshEvilGeek Is it possible to selectively disable swiping on individual edges?

Like setSwipeEnabled() but for each edge?

**Comment by wangbourne** [comment]
I'm  confused so I have to ask  
Have you done on the function of Swipe Views on Both Left and Right?

**Comment by iAviatorJose** [comment]
@HarshEvilGeek  @daimajia have guys completed with the swipe on both sides of a ListView Cell.

**Comment by HarshEvilGeek** [comment]
Hey, sorry, I've been a little busy. I do have a working fork with multiple edge swipe. I haven't generated a pull request, because there are a few more features (mainly around performance that I wanted to add first).

@wangbourne and @iAviatorJose , you can use my fork here https://github.com/HarshEvilGeek/AndroidSwipeLayout for now. I should be able to get to this next weekend, if I manage to clear up my backlog on my other projects. I know for a fact, I'll be free by the second weekend in Feb, so that's the absolute latest.

**Comment by iAviatorJose** [comment]
Thanks @HarshEvilGeek in between what programmatic changes i have to do .. i mean to say earlier we used  to have two layout inside the swipelayout now what new i have to do to for have swipe on both the sides with respect to the new changes.

**Comment by daimajia** [comment]
Hey @HarshEvilGeek , good news, AndroidSwipeLayout start support RecyclerView. Something has been changed,  please pull the latest code before generate a new PR. Thanks your hard work on it. :-D

**Comment by HarshEvilGeek** [comment]
@daimajia , I'm ready to make the changes, but when I merged with your repository the build broke. You seem to have added an attritbute swipe:horizontalSwipeOffset="" (but I don't see where this is coming from)

**Comment by HarshEvilGeek** [comment]
Hey, I've added all the features requested here. Namely, 1) findViewById() for each layout (will default to using the order if the user doesn't specify), 2) touchSlop changes, 3) Support for enabling/disabling swipe for each edge individually). @daimajia , and anyone who's requested for it, I'd recommend testing it (didn't do much testing after I merged your recycler view changes). Once you're done, let me know, I'll raise a pull request.

One issue I know about is occasionally, when you do a fast swipe from a right edge to a left edge (without any pause), the offset used is the wrong one (doesn't have enough time to update). This is pretty rare and a rather minor issue. There are a few hacks to fix it, but I'll take a look later.

**Comment by daimajia** [comment]
@HarshEvilGeek Great work!  I'll test your master branch, and will give feedback ASAP.

**Comment by daimajia** [comment]
@HarshEvilGeek  I quickly checked the every commits you made. And made some samples to test the functions. It works really well in `ListView`, `RecyclerView` and `GridView`. But there are still some tiny problems.
1. [`TypeArray` `a`](https://github.com/HarshEvilGeek/AndroidSwipeLayout/compare/daimajia:master...HarshEvilGeek:master#diff-b9836eda6b6b331ba8e8b58214d5da5aR95) should call `recycle()` to release memory. (this is my fault ^^).
2. `SwipeLayout` should own a new `open`  method, which can specify which DragEdge to open. [Check Here](https://github.com/HarshEvilGeek/AndroidSwipeLayout/blob/master/library/src/main/java/com/daimajia/swipe/SwipeLayout.java#L1321-L1351)

**Comment by HarshEvilGeek** [comment]
I've added the changes. Let me know if there's anything else.

**Comment by daimajia** [comment]
@HarshEvilGeek Well done!  
There is an imperfect part on the usage of the multi edges, when using multi edge, you have to call [`setDragEdges`](https://github.com/HarshEvilGeek/AndroidSwipeLayout/blob/master/library/src/main/java/com/daimajia/swipe/SwipeLayout.java#L1531-L1546) method. In a short time, it will not support top and bottom edges or other combination, just left and right. 

so, we can make it easier to use.  `SwipeLayout` can only own 2 or 3 children, if 2 then the common scenario , if 3, then multi edges scenario, we can call `setDragEdges` inside the `SwipeLayout`. how about that?

**Comment by HarshEvilGeek** [comment]
Hey, I'm not sure what you're talking about. I added a temp demo with 3 swipes (left, right, top). It doesn't look great because of some layout formatting, but it works perfectly. I needed to switch the coordinates for top and bottom, but aside from that. Check it out.

**Comment by daimajia** [comment]
@HarshEvilGeek  Oh, my fault! I still thought that it could only work in two edges... please ignore my previous suggestion, it's my bullshit... :laughing:

**Comment by daimajia** [comment]
@HarshEvilGeek I'm testing your master branch, wait a minute.

**Comment by daimajia** [comment]
@HarshEvilGeek  it's not easy to understand whit [-1](https://github.com/HarshEvilGeek/AndroidSwipeLayout/blob/master/demo/src/main/java/com/daimajia/swipedemo/MyActivity.java#L33) means. better set a  constant (`public static final`) variable. like SwipeLayout.EmptyLayout. or something.

**Comment by HarshEvilGeek** [comment]
Sure

**Comment by daimajia** [comment]
@HarshEvilGeek Awesome!  It's time to send a pull request.  I'll complete the wiki after merged. 
Really thanks for your hard work on this project. If you are available, and have interests, would you want be a collaborator of this repository ? (will have push access to this repo.) . :-D
just like @jpshelley , he is working on swipe dismiss recently, we both want to make AndroidSwipeLayout to be the most powerful Android component.

**Comment by HarshEvilGeek** [comment]
Great, if the changes are done, I need to get clearance for the pull request (only because I worked on this for my job). Will ask for it now, and I'll commit in a few days I hope. They just need to confirm I'm not sharing any proprietary code or anything.

**Comment by daimajia** [comment]
@HarshEvilGeek Wow, it sounds pretty strict. We'll waiting for your PR, how about join this project as a collaborator?

**Comment by HarshEvilGeek** [comment]
Yes, that sounds great!

**Comment by daimajia** [comment]
@HarshEvilGeek  Cool, I'll send you a confirmation via GitHub project settings. You'll get push access after be a member of this project！ :smiley:

**Comment by iAviatorJose** [comment]
@HarshEvilGeek  i checked your new changes in your forked repo its working superb.

**Comment by iAviatorJose** [comment]
@daimajia please integrate the new changes!!!

**Comment by daimajia** [comment]
@iAviatorJose Just like HarshEvilGeek said:
> Great, if the changes are done, I need to get clearance for the pull request (only because I worked on this for my job). Will ask for it now, and I'll commit in a few days I   hope. They just need to confirm I'm not sharing any proprietary code or anything.

Waiting for his PR.

**Comment by HarshEvilGeek** [comment]
Hey, just got approval for the PR, and to continue to work on this repository on my own time if I wish. @daimajia , do you want me to keep the top swipe on the first layout? Or should I remove it and then initiate the request. Or should I just go ahead?

**Comment by iAviatorJose** [comment]
@daimajia @HarshEvilGeek i suggest you guys to keep the Top Swipe. May Somebody needs to something like that in their project.

**Comment by daimajia** [comment]
Sorry for my delay reply. Recently it's Chinese new year. Happy new year to all of you. ^.^

@HarshEvilGeek  Agree with @iAviatorJose  Keep it~

**Comment by HarshEvilGeek** [comment]
Happy New Year, @daimajia . I assumed that's why you were busy :). Just raised the pull request. I definitely intended to keep the top swipe functionality. I just thought you might wanted me to take it off the first layout specifically for now, since it doesn't look that great (the star is quite small). Anyway, we can definitely modify that later.

I apologize for the delay, I'll be able to make changes much faster now (though I might have less time)

**Comment by iAviatorJose** [comment]
@daimajia Happy New Year!!!

**Comment by daimajia** [comment]
@HarshEvilGeek Merged ! ! !   I'll prettify the sample project right now. This issue can be closed. Thanks again!

**Comment by Jabelriera** [comment]
I have checked all the comments above and had a quick look at the library, but I am not sure if I have understood everything. I need to be able to do swipe right to left and left to right in a same ListView item with different actions (and layouts in the background). Is it possible ? 

I have seen the different swipe types but I am not sure if two swipe directions can be set at the same time with different results set.

Thank you very much for everythin, the lib looks amazing!

**Comment by dileepan** [comment]
@Jabelriera This is a code excerpt from the demo app in the MyActivity.java file. Hope those lines answers your question

sample1.setDragEdges(SwipeLayout.DragEdge.Left, SwipeLayout.DragEdge.Right, SwipeLayout.DragEdge.Top);
// When using multiple drag edges it's a good idea to pass the ids of the views that you're using for the left, right, top bottom views (-1 if you're not using a particular view)
sample1.setBottomViewIds(R.id.bottom_wrapper, R.id.bottom_wrapper_2, R.id.starbott, SwipeLayout.EMPTY_LAYOUT);

**Comment by Jabelriera** [comment]
Thank you very much @dileepan !

**Comment by rizwanbpatel** [comment]
Thank you guys @daimajia, @HarshEvilGeek, For a fantastic library for Swipe support. This helps alot in multiple edge swipe.
