### ISSUE TITLE
This library is piece of shit.

### ISSUE THREAD

**Issue by wksyw** [daimajia/AndroidSwipeLayout#422]
你这什么破框架，垃圾

What a shit framework, shit. (Translated by daimajia)

**Comment by nijian81** [comment]
很好用的啊，怎么垃圾了？？？

**Comment by daimajia** [comment]
Thanks @nijian81 . Close this useless issue. 

BTW. Be polite please, no one works for you. F**k You.

**Comment by AndroidUtils** [comment]
Describe the reason to us, not express your emotions。
BTW, you should learn how to ask a  question.  @wksyw 
http://stackoverflow.com/help/how-to-ask

**Comment by little4-lee** [comment]
A person in shit regards everything as shit.

**Comment by longtaoge** [comment]
Young  boy, don't be like this

**Comment by 7heaven** [comment]
Raised an issue without describing the detail of the problem you ran into is totally useless. emotional won't help.

**Comment by KevinRoy** [comment]
Do not do to others what you do not want others to do to you.

**Comment by gaelthas** [comment]
GLHF@wksyw

**Comment by gaelthas** [comment]
good luck boy @wksyw

**Comment by wksyw** [comment]
这个框架在我公司的测试机（魅蓝3）上有问题

**Comment by linq8261** [comment]
在魅蓝note3上的确有问题，滑动的过程中没有任何效果，松手之后自动滑动出来马上又缩回去了
