### ISSUE TITLE
setSwipeEnabled not working?

### ISSUE THREAD

**Issue by vaggelis-net** [daimajia/AndroidSwipeLayout#44]
Hey,
I tried disabling the swipe using this method but i didn't see any results. I was still able to swipe.
I checked a bit the source of [SwipeLayout.java](https://github.com/daimajia/AndroidSwipeLayout/blob/master/library/src/main/java/com/daimajia/swipe/SwipeLayout.java#L892) but the variable is just set and not used anywhere else in the code.

**Comment by Corey76** [comment]
Sometimes its useful to explain the error you had here

**Comment by de-Stan** [comment]
Hey, it's been a while and I don't remember what I did here but it was wrong implementation on my side. Even if I open that project now I won't remember exactly what was the problem. 
Post any issues you have and we will help you.
