### ISSUE TITLE
我发现item侧滑菜单可以同时滑出多个

### ISSUE THREAD

**Issue by xfhy** [daimajia/AndroidSwipeLayout#464]
我发现item侧滑菜单可以同时滑出多个,当同时按住几个item并同时滑出时,几个item的菜单都会被滑出来,虽然最后item只显示了一个,另外的被关闭了,但是还是不人性化.

**Comment by Mingyueyixi** [comment]
正常的吧。。。我发现QQ也可以滑出两个。偶然之下，我滑出的
