### ISSUE TITLE
fully open & closed mode cause to lags

### ISSUE THREAD

**Issue by yoavst** [daimajia/AndroidSwipeLayout#51]
When I opened it to the max or hide it, it has a lag, so I can't immediately swipe.

**Comment by mattiasbe** [comment]
@yoavst are you perhaps referring to the fact that you can't open/close it again unless you release the touch (if fully open/closed or close enough to or fully close/open that it closes/opens the rest of the way by itself)?

**Comment by mattiasbe** [comment]
Or maybe if you get too close to fully open/closed and it starts to move the last bit by itself, it feels a bit laggy as you work against that movement? IMHO that's a very minor point but it indeed should probably stop responding to dragging after initiating the automatic last movement.

**Comment by mattiasbe** [comment]
@jpshelley By the way, off topic, sorry but you mentioned RecyclerView support here, that seems to work fine already, I'm using it with v1.1.8 and it works great. Though the sample demo for it lacks some code.

**Comment by jpshelley** [comment]
@mattiasbe We just got merged in the RecyclerView support probably last week. If you feel there is an issue with it feel free to send a pull request.

**Comment by yoavst** [comment]
maybe it because of recyclerview support. I'll update the version and check it.

**Comment by mattiasbe** [comment]
@jpshelley (continued off topic, regarding recyclerview) nevermind, the demo was updated as well or I looked at an older tag, I vaguely recall it was missing calling the (parent's) mItemManager.bindView(..) and not even using the new RecyclerViewAdapter. Great work.

**Comment by yoavst** [comment]
Sorry, it is still here.
In the sample, try to swipe the layout in the main screen and then without leave the hand swipe it back (after it was fully open).

**Comment by daimajia** [comment]
@yoavst , this issue should be fixed in the latest version, when you available, check it.
