### ISSUE TITLE
Odd and even row background color

### ISSUE THREAD

**Issue by vnguyen972** [daimajia/AndroidSwipeLayout#67]
This might not be an issue but as a new user, I'm not sure how to go about implement this. I tried 

        if (position % 2 == 0) {
            view.setBackgroundColor(Color.parseColor("#ffffff"));
        } else {
            view.setBackgroundColor(Color.parseColor("#BCF7F0"));
        }

..on fillValues method but it doesn't do anything... I realized my layout xml specifies background colors but when I took it out, then I see the color in fillValues but when swiping to reveal the bottom layer... it looks funny. part of it was transparent when dragging.

Any tips?

**Comment by mattiasbe** [comment]
Do it in `fillValues` instead of `generateView` else the position will be wrong as you are seeing now.

**Comment by daimajia** [comment]
@vnguyen972  Please do as @mattiasbe say.
