### ISSUE TITLE
Scroll problem

### ISSUE THREAD

**Issue by weiyideai520** [daimajia/AndroidSwipeLayout#70]
1、open the first item
2、Scroll the listView
3、Items appearing later has open

I want to close them,who can i do?

**Comment by daimajia** [comment]
[The adapters](https://github.com/daimajia/AndroidSwipeLayout/tree/master/library/src/main/java/com/daimajia/swipe/adapters) I provided are support open status saving and restore. 

If you don't need that feature, just inherit your own adapter class from [BaseAdapter](http://developer.android.com/reference/android/widget/BaseAdapter.html).

Check [the wiki](https://github.com/daimajia/AndroidSwipeLayout/wiki/SwipeAdapter) to know more.
