### ISSUE TITLE
Smooth open when calling openItem(position)

### ISSUE THREAD

**Issue by djandreski** [daimajia/AndroidSwipeLayout#73]
I implemented a `ListView` with `ArraySwipeAdapter`. What I want is, when I click the ListItem, to swipe open it.
On Item click I called `openItem(position)` method,  and it did opened the underlaying view, the problem is that the transition is not smooth, it isn't animating to the final position.

I tried to modify the `openItem` method where I explicitly called the `open()` method of the selected SwipeLayout, but it didn't worked.

Can you provide this functionality, or give me some advice how to achieve this?

**Comment by daimajia** [comment]
hey, guy.

try this 

```java

mListView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                ((SwipeLayout)(mListView.getChildAt(position - mListView.getFirstVisiblePosition()))).open(true);
            }
        });

```
