### ISSUE TITLE
Control AndroidSwipeLayout Effective or not Effective

### ISSUE THREAD

**Issue by xiaomeixw** [daimajia/AndroidSwipeLayout#75]
删除功能并不是所有的情况都会出现，如何控制AndroidSwipeLayout只显示SurfaceView，底部的BottomView不想在某种特定的情况下使用。没有看到有相关的参数进行控制？望告知并fix

**Comment by xiaomeixw** [comment]
this is my Situation： I don't want to use the AndroidSwipeLayout in some Special circumstances，I want show SurfaceView ，but not show BottomView in this Special circumstances。can you have Parameters to  control this situation？

**Comment by xiaomeixw** [comment]
I am sorry ，I read your source code find have a Parameters to control this situation：
so I had solved this Q，this is my code ，I want to help someone who have this Q like me：
swipeLayout = (SwipeLayout) view.findViewById(getSwipeLayoutResourceId(position));
if(isMySelf){
		swipeLayout.setSwipeEnabled(true);
	}else{
		swipeLayout.setSwipeEnabled(false);
}
Thank you for your open source code ！

**Comment by daimajia** [comment]
just use the method `setSwipeEnable`.
https://github.com/daimajia/AndroidSwipeLayout/blob/master/library/src/main/java/com/daimajia/swipe/SwipeLayout.java#L884

**Comment by daimajia** [comment]
Solved the problem?

**Comment by xiaomeixw** [comment]
Of course Solved，Thanks.....

**Comment by mattiasbe** [comment]
Should be closed.
