### ISSUE TITLE
Surface view isn't clickable.

### ISSUE THREAD

**Issue by shantanuraj** [daimajia/AndroidSwipeLayout#76]
The surface view doesn't trigger the onClickListener on touch. 
Example:
In my swipe layout, the top surface is a CardView, and some Layout as bottom view.
I want to trigger an Intent launch when my CardView is clicked, but that doesn't happen.
The layout can either be swipable or clickable, not both at the same time.

**Comment by mattiasbe** [comment]
Make it swipable and clickablebut in your click listener check if the SwipeLayout status is Close, something like:
    public void onClick(View view) {
        SwipeLayout swipeLayout = (SwipeLayout) view;
        if (swipeLayout.getOpenStatus() == SwipeLayout.Status.Close) {
            ...
        }
    }

**Comment by mattiasbe** [comment]
Actually I agree, the above extra check only helps if you use it in a `RecyclerItemClickListener` and then not always (focus needed too?).

**Comment by mattiasbe** [comment]
Example code:
```
recyclerView.addOnItemTouchListener(new RecyclerItemClickListener(getActivity(), new RecyclerItemClickListener.OnItemClickListener() {
            @Override
            public void onItemClick(View view, int position) {
                SwipeLayout swipeLayout = (SwipeLayout) view;
                if (swipeLayout.getOpenStatus() != SwipeLayout.Status.Open) {
                    onClick(true, position);
                }
            }
        }));
```
But sometimes you get a click indication but nothing happens?

**Comment by linfaxin** [comment]
try this PR: https://github.com/daimajia/AndroidSwipeLayout/pull/106

**Comment by daimajia** [comment]
https://github.com/daimajia/AndroidSwipeLayout/blob/master/demo/src/main/java/com/daimajia/swipedemo/MyActivity.java#L44 This feature has been added. :-D
