### ISSUE TITLE
Trigger action and close layout after swiping

### ISSUE THREAD

**Issue by gnuhel** [daimajia/AndroidSwipeLayout#83]
It is possible to trigger an action and close the layout after swiping the surface?

**Comment by mattiasbe** [comment]
Add a ´SwipeLayout.SwipeListener´ (use ´SimpleSwipeListener`) and override and trigger your action in `onOpen()`

**Comment by gnuhel** [comment]
does it close the surface automatically? or do I have to do it manually?
if yes, how could I do it? Thanks

**Comment by mattiasbe** [comment]
Updated my answer while you replied with exactly that, need to call `close()` as well onthe layout to get as a parameter in `onOpen`

**Comment by gnuhel** [comment]
cool thanks
