### ISSUE TITLE
Buttons can't be swiped on to scroll the SwipeLayout

### ISSUE THREAD

**Issue by DBradyIE** [daimajia/AndroidSwipeLayout#94]
If there is a button or any clickable layout in your SwipeLayout it intercepts all swipe gestures and you can't swipe on top of it to scroll the SwipeLayout.

For example in ListView in the demo application you can't swipe on the "Yes,Delete" button to close the Swipelayout. Perhaps the ["canScroll"](http://developer.android.com/reference/android/view/View.html#canScrollHorizontally(int)) methods  need to be used before handing over all the touch events.

**Comment by linfaxin** [comment]
Try this RP: https://github.com/daimajia/AndroidSwipeLayout/pull/106

**Comment by eloudsa** [comment]
I already noticed this issue.

Is there any fix and when should it be available?
