### ISSUE TITLE
cannot resolve methods setDragEdges and setBottomViewIds.

### ISSUE THREAD

**Issue by iAviatorJose** [daimajia/AndroidSwipeLayout#96]
I have used the new compile statement 
    compile "com.daimajia.swipelayout:library:1.1.8@aar"
But i get the following error: 
 cannot Resolve method setDragEdges and setBottomViewIds and Also the same for
SwipeLayout.EMPTY_LAYOUT.

Following is image Describing the Problem
![swipe](https://cloud.githubusercontent.com/assets/8208627/6389868/c0161872-bdcd-11e4-8977-4f2157dfd6b0.png)

**Comment by iAviatorJose** [comment]
![Uploading swipe.png . . .]()

**Comment by iAviatorJose** [comment]
I think the new changes made by @HarshEvilGeek  have not been reflected in the new version,

**Comment by HarshEvilGeek** [comment]
Considering that the methods that aren't resolved are from the newer code, I'm guessing that you didn't do a clean build (you'll need to, otherwise gradlew won't rebuild the required files). Or you have updated your code after my changes were merged.

**Comment by iAviatorJose** [comment]
I did try clean and rebuilding the project even that did not help me.
So i made a sample project with the new Compile Statement still got the same error.
The image above posted is of the sample project i tried.

**Comment by Studentessa** [comment]
Hello, I'm having the same problem! 
I've tried clean the proyect as well!

**Comment by iAviatorJose** [comment]
Yup setDragEdge(..) is from the older version 1.1.7 but for setDragEdges(..) we are getting this problem

**Comment by Studentessa** [comment]
I'm using eclipse, so I'm using the lib as .jar. I thought it could be related to that, may be the .jar file isn't updated! 
(but AviatorJose is using AndroidStudio, :s )

**Comment by iAviatorJose** [comment]
@Studentessa  i have tried both the jar and the compile statement in Android Studio bot are not working

**Comment by iAviatorJose** [comment]
@daimajia and @HarshEvilGeek frriends did you find any solution to this issue ?

**Comment by tianchi-seattle** [comment]
It would be great to have the drag multiple edges feature. I am waiting here too.

**Comment by HarshEvilGeek** [comment]
@iAviatorJose I'm a little confused, didn't you test my repo out and say it was working for you? My code is merged with the master branch and they are exactly the same. If it's not working, it probably means your code hasn't been updated or something hasn't been built correctly. If you're using Android Studio, please select the "rebuild" option under build and run it again. Please confirm that your code is up to date, because it's working perfectly for me

**Comment by HarshEvilGeek** [comment]
@tianchi-seattle this feature has already been tested and added. Please see the sample code for details on how to incorporate bi directional swipe.

**Comment by tianchi-seattle** [comment]
@iAviatorJose @HarshEvilGeek Ahh I figured it out. We need to use library:1.1.9@aar instead of 1.1.8 at gradle build file. Please update it on the wiki page! Thanks.

**Comment by HarshEvilGeek** [comment]
Oh, didn't realize you were using the jar. Yup, 1.1.9

**Comment by Studentessa** [comment]
I'm using .jar file, and i downloaded the one in the wiki: AndroidSwipeLayout-1.1.8.jar. Could you update it?

Tanks

**Comment by iAviatorJose** [comment]
@HarshEvilGeek  @daimajia  I did test your repo and it did work for me. But when i referred the documentation i saw the version as 1.1.8 and i assumed that to be as the new updated version of the repo. 

Ok Guys the new the new Version 1.1.9

use the following compile statement for Android Studio.

    compile "com.daimajia.swipelayout:library:1.1.9@aar"

We close these issue officially.

Thank you everyone.
