### ISSUE TITLE
swipe listview rigth&left as in demo gif?

### ISSUE THREAD

**Issue by Studentessa** [daimajia/AndroidSwipeLayout#97]
Hello:

Thanks for this lib and the tutorial, it is so easy and clear.
I want to implement listview with swipe to the rigth and to the left, as demo, but i dont know how, could you help me?

I had implemented listview adapter and it's working fine with swipe to the left.

regards!

**Comment by daimajia** [comment]
Check this https://github.com/daimajia/AndroidSwipeLayout/blob/master/demo/src/main/java/com/daimajia/swipedemo/MyActivity.java#L29-L71

https://github.com/daimajia/AndroidSwipeLayout/blob/master/demo/src/main/res/layout/sample1.xml

**Comment by Studentessa** [comment]
Thanks (I didn't see it), That's rigth!
Now, I dont know why I'm getting setDragEdges() is undefined for the type SwipeLayout.
